sites = {
    "01": {
        'name': 'ANTIOQUIA',
        'municipality': {
            '001': 'MEDELLIN',
            '004': 'ABEJORRAL',
            '007': 'ABRIAQUI',
            '010': 'ALEJANDRIA',
            '013': 'AMAGA',
            '016': 'AMALFI',
            '019': 'ANDES',
            '022': 'ANGELOPOLIS',
            '025': 'ANGOSTURA',
            '028': 'ANORI',
            '031': 'ANTIOQUIA',
            '034': 'ANZA',
            '035': 'APARTADO',
            '037': 'ARBOLETES',
            '039': 'ARGELIA',
            '040': 'ARMENIA',
            '043': 'BARBOSA',
            '046': 'BELMIRA',
            '049': 'BELLO',
            '052': 'BETANIA',
            '055': 'BETULIA',
            '058': 'BOLIVAR',
            '061': 'BURITICA',
            '062': 'BRICE/O',
            '064': 'CACERES',
            '067': 'CAICEDO',
            '070': 'CALDAS',
            '073': 'CAMPAMENTO',
            '076': 'CA/ASGORDAS',
            '078': 'CARACOLI',
            '079': 'CARAMANTA',
            '080': 'CAREPA',
            '082': 'CARMEN DE VIBORAL',
            '085': 'CAROLINA',
            '088': 'CAUCASIA',
            '091': 'CISNEROS',
            '094': 'COCORNA',
            '097': 'CONCEPCION',
            '100': 'CONCORDIA',
            '103': 'COPACABANA',
            '106': 'CHIGORODO',
            '109': 'DABEIBA',
            '112': 'DON MATIAS',
            '115': 'EBEJICO',
            '117': 'EL BAGRE',
            '118': 'ENTRERRIOS',
            '121': 'ENVIGADO',
            '124': 'FREDONIA',
            '127': 'FRONTINO',
            '130': 'GIRALDO',
            '133': 'GIRARDOTA',
            '136': 'GOMEZ PLATA',
            '139': 'GRANADA',
            '140': 'GUADALUPE',
            '142': 'GUARNE',
            '145': 'GUATAPE',
            '148': 'HELICONIA',
            '150': 'HISPANIA',
            '151': 'ITAGUI',
            '154': 'ITUANGO',
            '157': 'JARDIN',
            '160': 'JERICO',
            '163': 'LA CEJA',
            '166': 'LA ESTRELLA',
            '168': 'PUERTO NARE‐LA MAGDALENA',
            '169': 'LA UNION',
            '170': 'LA PINTADA',
            '172': 'LIBORINA',
            '175': 'MACEO',
            '178': 'MARINILLA',
            '181': 'MONTEBELLO',
            '184': 'MURINDO',
            '187': 'MUTATA',
            '190': 'NARI/O',
            '191': 'NECHI',
            '192': 'NECOCLI',
            '193': 'OLAYA',
            '196': 'PE/OL',
            '199': 'PEQUE',
            '202': 'PUEBLORRICO',
            '205': 'PUERTO BERRIO',
            '206': 'PUERTO TRIUNFO',
            '208': 'REMEDIOS',
            '211': 'RETIRO',
            '214': 'RIONEGRO',
            '217': 'SABANALARGA',
            '218': 'SABANETA',
            '220': 'SALGAR',
            '223': 'SAN ANDRES',
            '226': 'SAN CARLOS',
            '227': 'SAN FRANCISCO',
            '229': 'SAN JERONIMO',
            '230': 'SAN JOSE DE LA MONTA/A',
            '231': 'SAN JUAN DE URABA',
            '232': 'SAN LUIS',
            '235': 'SAN PEDRO',
            '237': 'SAN PEDRO DE URABA',
            '238': 'SAN RAFAEL',
            '241': 'SAN ROQUE',
            '244': 'SAN VICENTE',
            '247': 'SANTA BARBARA',
            '250': 'SANTA ROSA DE OSOS',
            '253': 'SANTO DOMINGO',
            '256': 'SANTUARIO',
            '259': 'SEGOVIA',
            '262': 'SONSON',
            '265': 'SOPETRAN',
            '268': 'TAMESIS',
            '270': 'TARAZA',
            '271': 'TARSO',
            '274': 'TITIRIBI',
            '277': 'TOLEDO',
            '280': 'TURBO',
            '282': 'URAMITA',
            '283': 'URRAO',
            '286': 'VALDIVIA',
            '289': 'VALPARAISO',
            '290': 'VEGACHI',
            '291': 'VIGIA DEL FUERTE',
            '292': 'VENECIA',
            '293': 'YALI',
            '295': 'YARUMAL',
            '298': 'YOLOMBO',
            '300': 'YONDO‐CASABE',
            '301': 'ZARAGOZA',
        },
    },
    "03": {
        'name': 'ATLANTICO',
        'municipality': {'001': 'BARRANQUILLA',
                '004': 'BARANOA',
                '007': 'CAMPO DE LA CRUZ',
                '010': 'CANDELARIA',
                '013': 'GALAPA',
                '016': 'JUAN DE ACOSTA',
                '019': 'LURUACO',
                '022': 'MALAMBO',
                '025': 'MANATI',
                '028': 'PALMAR DE VARELA',
                '031': 'PIOJO',
                '034': 'POLONUEVO',
                '035': 'PONEDERA',
                '037': 'PUERTO COLOMBIA',
                '040': 'REPELON',
                '043': 'SABANAGRANDE',
                '046': 'SABANALARGA',
                '047': 'SANTA LUCIA',
                '049': 'SANTO TOMAS',
                '052': 'SOLEDAD',
                '055': 'SUAN',
                '058': 'TUBARA',
                '061': 'USIACURI', },
    },
    "05": {
        'name': 'BOLIVAR',
        'municipality': {
            '001': 'CARTAGENA',
            '004': 'ACHI',
            '005': 'ARENAL',
            '006': 'ALTOS DEL ROSARIO',
            '007': 'ARJONA',
            '009': 'ARROYO HONDO',
            '010': 'BARRANCO DE LOBA',
            '013': 'CALAMAR',
            '014': 'CANTAGALLO',
            '015': 'CICUCO',
            '016': 'CORDOBA',
            '018': 'CLEMENCIA',
            '022': 'EL CARMEN DE BOLIVAR',
            '025': 'EL GUAMO',
            '026': 'HATILLO DE LOBA',
            '027': 'EL PE/ON',
            '028': 'MAGANGUE',
            '031': 'MAHATES',
            '037': 'MARGARITA',
            '040': 'MARIA LA BAJA',
            '041': 'MONTECRISTO',
            '043': 'MOMPOS',
            '044': 'MORALES',
            '050': 'NOROSI',
            '059': 'PINILLOS',
            '063': 'REGIDOR',
            '065': 'RIOVIEJO',
            '070': 'SAN ESTANISLAO',
            '072': 'SAN CRISTOBAL',
            '073': 'SAN FERNANDO',
            '076': 'SAN JACINTO',
            '078': 'SAN JACINTO DEL CAUCA',
            '079': 'SAN JUAN NEPOMUCENO',
            '082': 'SAN MARTIN DE LOBA',
            '084': 'SAN PABLO',
            '091': 'SANTA CATALINA',
            '094': 'SANTA ROSA',
            '095': 'SANTA ROSA DEL SUR',
            '097': 'SIMITI',
            '106': 'SOPLAVIENTO',
            '110': 'TALAIGUA NUEVO',
            '113': 'TIQUISIO (PTO. RICO)',
            '118': 'TURBACO',
            '121': 'TURBANA',
            '124': 'VILLANUEVA',
            '127': 'ZAMBRANO',
        },
    },
    "07": {
        'name': 'BOYACA',
        'municipality': {
            '001': 'TUNJA',
            '007': 'ALMEIDA',
            '008': 'AQUITANIA (PUEBLOVIEJO)',
            '010': 'ARCABUCO',
            '013': 'BELEN',
            '016': 'BERBEO',
            '019': 'BETEITIVA',
            '022': 'BOAVITA',
            '025': 'BOYACA',
            '028': 'BRICE/O',
            '031': 'BUENAVISTA',
            '034': 'BUSBANZA',
            '037': 'CALDAS',
            '040': 'CAMPOHERMOSO',
            '043': 'CERINZA',
            '046': 'CIENEGA',
            '049': 'COMBITA',
            '052': 'COPER',
            '055': 'CORRALES',
            '058': 'COVARACHIA',
            '059': 'CUBARA',
            '060': 'CUCAITA',
            '061': 'CUITIVA',
            '064': 'CHINAVITA',
            '067': 'CHIQUINQUIRA',
            '068': 'CHIQUIZA',
            '070': 'CHISCAS',
            '073': 'CHITA',
            '076': 'CHITARAQUE',
            '077': 'CHIVATA',
            '078': 'CHIVOR',
            '079': 'DUITAMA',
            '082': 'EL COCUY',
            '085': 'EL ESPINO',
            '088': 'FIRAVITOBA',
            '091': 'FLORESTA',
            '094': 'GACHANTIVA',
            '097': 'GAMEZA',
            '100': 'GARAGOA',
            '103': 'GUACAMAYAS',
            '106': 'GUATEQUE',
            '109': 'GUAYATA',
            '112': 'GUICAN',
            '118': 'IZA',
            '121': 'JENESANO',
            '124': 'JERICO',
            '127': 'LABRANZAGRANDE',
            '130': 'LA CAPILLA',
            '136': 'LA UVITA',
            '137': 'LA VICTORIA',
            '139': 'VILLA DE LEIVA',
            '142': 'MACANAL',
            '148': 'MARIPI',
            '151': 'MIRAFLORES',
            '154': 'MONGUA',
            '157': 'MONGUI',
            '160': 'MONIQUIRA',
            '161': 'MOTAVITA',
            '163': 'MUZO',
            '166': 'NOBSA',
            '169': 'NUEVO COLON',
            '173': 'OICATA',
            '176': 'OTANCHE',
            '178': 'PACHAVITA',
            '179': 'PAEZ',
            '181': 'PAIPA',
            '184': 'PAJARITO',
            '187': 'PANQUEBA',
            '190': 'PAUNA',
            '193': 'PAYA',
            '199': 'PAZ DE RIO',
            '202': 'PESCA',
            '205': 'PISBA',
            '214': 'PUERTO BOYACA',
            '215': 'QUIPAMA',
            '217': 'RAMIRIQUI',
            '220': 'RAQUIRA',
            '223': 'RONDON',
            '226': 'SABOYA',
            '232': 'SACHICA',
            '235': 'SAMACA',
            '237': 'SAN EDUARDO',
            '238': 'SAN JOSE DE PARE',
            '241': 'SAN LUIS DE GACENO',
            '247': 'SAN MATEO',
            '248': 'SAN MIGUEL DE SEMA',
            '249': 'SAN PABLO DE BORBUR',
            '250': 'SANTANA',
            '251': 'SANTA MARIA',
            '253': 'SANTA ROSA DE VITERBO',
            '256': 'SANTA SOFIA',
            '259': 'SATIVANORTE',
            '262': 'SATIVASUR',
            '265': 'SIACHOQUE',
            '268': 'SOATA',
            '271': 'SOCOTA',
            '274': 'SOCHA',
            '277': 'SOGAMOSO',
            '280': 'SOMONDOCO',
            '281': 'SORA',
            '282': 'SORACA',
            '283': 'SOTAQUIRA',
            '286': 'SUSACON',
            '289': 'SUTAMARCHAN',
            '292': 'SUTATENZA',
            '298': 'TASCO',
            '301': 'TENZA',
            '304': 'TIBANA',
            '307': 'TIBASOSA',
            '310': 'TINJACA',
            '311': 'TIPACOQUE',
            '313': 'TOCA',
            '316': 'TOGUI',
            '319': 'TOPAGA',
            '322': 'TOTA',
            '324': 'TUNUNGUA',
            '325': 'TURMEQUE',
            '328': 'TUTA',
            '331': 'TUTAZA',
            '334': 'UMBITA',
            '337': 'VENTAQUEMADA',
            '340': 'VIRACACHA',
            '346': 'ZETAQUIRA',
        },
    },
    "09": {
        'name': 'CALDAS',
        'municipality': {
            '001': 'MANIZALES',
            '004': 'AGUADAS',
            '007': 'ANSERMA',
            '013': 'ARANZAZU',
            '022': 'BELALCAZAR',
            '034': 'CHINCHINA',
            '037': 'FILADELFIA',
            '049': 'LA DORADA',
            '052': 'LA MERCED',
            '055': 'MANZANARES',
            '058': 'MARMATO',
            '061': 'MARQUETALIA',
            '067': 'MARULANDA',
            '076': 'NEIRA',
            '078': 'NORCASIA',
            '079': 'PACORA',
            '082': 'PALESTINA',
            '085': 'PENSILVANIA',
            '103': 'RIOSUCIO',
            '106': 'RISARALDA',
            '109': 'SALAMINA',
            '115': 'SAMANA',
            '120': 'SAN JOSE',
            '124': 'SUPIA',
            '127': 'VICTORIA',
            '130': 'VILLAMARIA',
            '133': 'VITERBO',
        },
    },
    "11": {
        'name': 'CAUCA',
        'municipality': {
            '001': 'POPAYAN',
            '004': 'ALMAGUER',
            '005': 'ARGELIA',
            '006': 'BALBOA',
            '007': 'BOLIVAR',
            '010': 'BUENOS AIRES',
            '013': 'CAJIBIO',
            '016': 'CALDONO',
            '019': 'CALOTO',
            '022': 'CORINTO',
            '025': 'EL TAMBO',
            '027': 'FLORENCIA',
            '028': 'GUAPI',
            '029': 'GUACHENE',
            '031': 'INZA',
            '034': 'JAMBALO',
            '037': 'LA SIERRA',
            '040': 'LA VEGA',
            '043': 'LOPEZ (MICAY)',
            '046': 'MERCADERES',
            '049': 'MIRANDA',
            '052': 'MORALES',
            '053': 'PADILLA',
            '055': 'PAEZ (BELALCAZAR)',
            '058': 'PATIA (EL BORDO)',
            '060': 'PIAMONTE',
            '061': 'PIENDAMO',
            '064': 'PUERTO TEJADA',
            '067': 'PURACE (COCONUCO)',
            '070': 'ROSAS',
            '073': 'SAN SEBASTIAN',
            '076': 'SANTANDER DE QUILICHAO',
            '079': 'SANTA ROSA',
            '082': 'SILVIA',
            '085': 'SOTARA (PAISPAMBA)',
            '086': 'SUCRE',
            '087': 'SUAREZ',
            '088': 'TIMBIO',
            '091': 'TIMBIQUI',
            '094': 'TORIBIO',
            '097': 'TOTORO',
            '098': 'VILLA RICA',
        },
    },
    "12": {
        'name': 'CESAR',
        'municipality': {
            '001': 'VALLEDUPAR',
            '075': 'AGUACHICA',
            '150': 'AGUSTIN CODAZZI',
            '170': 'ASTREA',
            '180': 'BECERRIL',
            '200': 'BOSCONIA',
            '225': 'CURUMANI',
            '300': 'CHIMICHAGUA',
            '375': 'CHIRIGUANA',
            '410': 'EL COPEY',
            '415': 'EL PASO',
            '450': 'GAMARRA',
            '525': 'GONZALEZ',
            '600': 'LA GLORIA',
            '608': 'LA JAGUA DE IBIRICO',
            '625': 'MANAURE BALCON DEL CESAR (MANA',
            '650': 'PAILITAS',
            '700': 'PELAYA',
            '720': 'PUEBLO BELLO',
            '750': 'RIO DE ORO',
            '800': 'SAN ALBERTO',
            '825': 'LA PAZ',
            '850': 'SAN DIEGO',
            '875': 'SAN MARTIN',
            '900': 'TAMALAMEQUE',
        },
    },
    "13": {
        'name': 'CORDOBA',
        'municipality': {
            '001': 'MONTERIA',
            '004': 'AYAPEL',
            '007': 'BUENAVISTA',
            '009': 'CANALETE',
            '010': 'CERETE',
            '013': 'CIENAGA DE ORO',
            '014': 'COTORRA (BONGO)',
            '016': 'CHIMA',
            '019': 'CHINU',
            '020': 'LA APARTADA (FRONTERA)',
            '022': 'LORICA',
            '023': 'LOS CORDOBAS',
            '024': 'MOMIL',
            '025': 'MONTELIBANO',
            '027': 'MO/ITOS',
            '028': 'PLANETA RICA',
            '031': 'PUEBLO NUEVO',
            '032': 'PUERTO LIBERTADOR',
            '033': 'PUERTO ESCONDIDO',
            '034': 'PURISIMA',
            '037': 'SAHAGUN',
            '040': 'SAN ANDRES DE SOTAVENTO',
            '043': 'SAN ANTERO',
            '046': 'SAN BERNARDO DEL VIENTO',
            '049': 'SAN CARLOS',
            '052': 'SAN JOSE DE URE',
            '055': 'SAN PELAYO',
            '058': 'TIERRALTA',
            '060': 'TUCHIN',
            '061': 'VALENCIA',
        },
    },
    "15": {
        'name': 'CUNDINAMARCA',
        'municipality': {
            '001': 'BOGOTA D.C',
            '004': 'AGUA DE DIOS',
            '007': 'ALBAN',
            '010': 'ANAPOIMA',
            '013': 'ANOLAIMA',
            '016': 'ARBELAEZ',
            '019': 'BELTRAN',
            '022': 'BITUIMA',
            '025': 'BOJACA',
            '029': 'CABRERA',
            '030': 'CACHIPAY',
            '031': 'CAJICA',
            '034': 'CAPARRAPI',
            '037': 'CAQUEZA',
            '040': 'CARMEN DE CARUPA',
            '043': 'COGUA',
            '046': 'COTA',
            '049': 'CUCUNUBA',
            '052': 'CHAGUANI',
            '055': 'CHIA',
            '058': 'CHIPAQUE',
            '061': 'CHOACHI',
            '064': 'CHOCONTA',
            '067': 'EL COLEGIO',
            '070': 'EL PE/ON',
            '072': 'EL ROSAL',
            '076': 'FACATATIVA',
            '079': 'FOMEQUE',
            '085': 'FOSCA',
            '088': 'FUNZA',
            '091': 'FUQUENE',
            '094': 'FUSAGASUGA',
            '097': 'GACHALA',
            '100': 'GACHANCIPA',
            '103': 'GACHETA',
            '106': 'GAMA',
            '109': 'GIRARDOT',
            '112': 'GUACHETA',
            '115': 'GUADUAS',
            '118': 'GUASCA',
            '121': 'GUATAQUI',
            '124': 'GUATAVITA',
            '127': 'GUAYABAL DE SIQUIMA',
            '128': 'GUAYABETAL',
            '130': 'GUTIERREZ',
            '132': 'GRANADA',
            '133': 'JERUSALEN',
            '136': 'JUNIN',
            '139': 'LA CALERA',
            '142': 'LA MESA',
            '145': 'LA PALMA',
            '148': 'LA PE/A',
            '151': 'LA VEGA',
            '154': 'LENGUAZAQUE',
            '157': 'MACHETA',
            '160': 'MADRID',
            '163': 'MANTA',
            '166': 'MEDINA',
            '169': 'MOSQUERA',
            '172': 'NARI/O',
            '175': 'NEMOCON',
            '178': 'NILO',
            '181': 'NIMAIMA',
            '184': 'NOCAIMA',
            '190': 'PACHO',
            '193': 'PAIME',
            '196': 'PANDI',
            '198': 'PARATEBUENO (LA NAGUAYA)',
            '199': 'PASCA',
            '202': 'PUERTO SALGAR',
            '205': 'PULI',
            '208': 'QUEBRADANEGRA',
            '211': 'QUETAME',
            '214': 'QUIPILE',
            '217': 'APULO',
            '218': 'RICAURTE',
            '220': 'SAN ANTONIO DEL TEQUENDAMA',
            '223': 'SAN BERNARDO',
            '226': 'SAN CAYETANO',
            '229': 'SAN FRANCISCO',
            '232': 'SAN JUAN DE RIOSECO',
            '235': 'SASAIMA',
            '238': 'SESQUILE',
            '239': 'SIBATE',
            '241': 'SILVANIA',
            '244': 'SIMIJACA',
            '247': 'SOACHA',
            '250': 'SOPO',
            '256': 'SUBACHOQUE',
            '259': 'SUESCA',
            '262': 'SUPATA',
            '265': 'SUSA',
            '268': 'SUTATAUSA',
            '271': 'TABIO',
            '274': 'TAUSA',
            '277': 'TENA',
            '280': 'TENJO',
            '283': 'TIBACUY',
            '286': 'TIBIRITA',
            '289': 'TOCAIMA',
            '292': 'TOCANCIPA',
            '295': 'TOPAIPI',
            '298': 'UBALA',
            '301': 'UBAQUE',
            '304': 'UBATE',
            '307': 'UNE',
            '316': 'UTICA',
            '318': 'VENECIA',
            '319': 'VERGARA',
            '322': 'VIANI',
            '323': 'VILLAGOMEZ',
            '325': 'VILLAPINZON',
            '328': 'VILLETA',
            '331': 'VIOTA',
            '334': 'YACOPI',
            '337': 'ZIPACON',
            '340': 'ZIPAQUIRA',
        },
    },
    "16": {
        'name': 'BOGOTA D.C',
        'municipality': {
            '001': 'BOGOTA D.C',
        },
    },
    "17": {
        'name': 'CHOCO',
        'municipality': {
            '001': 'QUIBDO',
            '002': 'ATRATO (YUTO)',
            '004': 'ACANDI',
            '006': 'ALTO BAUDO (PIE DE PATO)',
            '007': 'BAGADO',
            '008': 'BAHIA SOLANO (MUTIS)',
            '010': 'BAJO BAUDO (PIZARRO)',
            '011': 'BOJAYA (BELLAVISTA)',
            '012': 'MEDIO ATRATO (BETE)',
            '013': 'CONDOTO',
            '014': 'CERTEGUI',
            '015': 'CARMEN DEL DARIEN',
            '016': 'EL CARMEN',
            '017': 'EL CANTON DEL SAN PABLO (MAN.',
            '019': 'ISTMINA',
            '022': 'JURADO',
            '025': 'LLORO',
            '026': 'MEDIO BAUDO (PUERTO MELUK)',
            '027': 'MEDIO SAN JUAN',
            '028': 'NOVITA',
            '031': 'NUQUI',
            '032': 'RIO IRO',
            '034': 'RIOSUCIO',
            '035': 'RIO QUITO (PAIMADO)',
            '037': 'SAN JOSE DEL PALMAR',
            '038': 'EL LITORAL DEL SAN JUAN',
            '040': 'SIPI',
            '043': 'TADO',
            '048': 'UNGUIA',
            '060': 'UNION PAnameRICANA (LAS ANIMAS',
        },
    },
    "19": {
        'name': 'HUILA',
        'municipality': {
            '001': 'NEIVA',
            '004': 'ACEVEDO',
            '007': 'AGRADO',
            '010': 'AIPE',
            '013': 'ALGECIRAS',
            '016': 'ALTAMIRA',
            '019': 'BARAYA',
            '022': 'CAMPOALEGRE',
            '025': 'TESALIA (CARNICERIAS)',
            '028': 'COLOMBIA',
            '031': 'ELIAS',
            '034': 'GARZON',
            '037': 'GIGANTE',
            '040': 'GUADALUPE',
            '043': 'HOBO',
            '044': 'ISNOS',
            '046': 'IQUIRA',
            '047': 'LA ARGENTINA (PLATA VIEJA)',
            '049': 'LA PLATA',
            '050': 'NATAGA',
            '051': 'OPORAPA',
            '052': 'PAICOL',
            '055': 'PALERMO',
            '056': 'PALESTINA',
            '058': 'PITAL',
            '061': 'PITALITO',
            '064': 'RIVERA',
            '067': 'SALADOBLANCO',
            '070': 'SAN AGUSTIN',
            '074': 'SANTA MARIA',
            '076': 'SUAZA',
            '079': 'TARQUI',
            '082': 'TELLO',
            '085': 'TERUEL',
            '088': 'TIMANA',
            '091': 'VILLAVIEJA',
            '094': 'YAGUARA',
        },
    },
    "21": {
        'name': 'MAGDALENA',
        'municipality': {
            '001':'SANTA MARTA',
            '008':'ALGARROBO',
            '010':'ARACATACA',
            '012':'ARIGUANI (EL DIFICIL)',
            '013':'CERRO DE SAN ANTONIO',
            '015':'CHIVOLO',
            '016':'CIENAGA',
            '020':'CONCORDIA',
            '025':'EL BANCO',
            '028':'EL PI/ON',
            '030':'EL RETEN',
            '031':'FUNDACION',
            '040':'GUAMAL',
            '042':'NUEVA GRANADA',
            '046':'PEDRAZA',
            '048':'PIJI/O DEL CARMEN',
            '049':'PIVIJAY',
            '052':'PLATO',
            '055':'PUEBLOVIEJO',
            '058':'REMOLINO',
            '060':'SABANAS DE SAN ANGEL',
            '067':'SALAMINA',
            '070':'SAN SEBASTIAN DE BUENAVISTA',
            '073':'SAN ZENON',
            '076':'SANTA ANA',
            '078':'SANTA BARBARA DE PINTO',
            '079':'SITIONUEVO',
            '085':'TENERIFE',
            '090':'ZAPAYAN',
            '095':'ZONA BANANERA (SEVILLA)',
        },
    },
    "23": {
        'name': 'NARIÑO',
        'municipality': {
            '001': 'PASTO',
            '004': 'ALBAN (SAN JOSE)',
            '007': 'ALDANA',
            '010': 'ANCUYA',
            '013': 'ARBOLEDA (BERRUECOS)',
            '016': 'BARBACOAS',
            '017': 'BELEN',
            '019': 'BUESACO',
            '022': 'COLON (GENOVA)',
            '025': 'CONSACA',
            '028': 'CONTADERO',
            '031': 'CORDOBA',
            '034': 'CUASPUD (CARLOSAMA)',
            '037': 'CUMBAL',
            '038': 'CHACHAGUI',
            '039': 'CUMBITARA',
            '040': 'EL ROSARIO',
            '041': 'EL CHARCO',
            '043': 'EL TABLON',
            '044': 'EL PE/OL',
            '046': 'EL TAMBO',
            '047': 'FRANCISCO PIZARRO (SALAHONDA)',
            '049': 'FUNES',
            '052': 'GUACHUCAL',
            '055': 'GUAITARILLA',
            '058': 'GUALMATAN',
            '061': 'ILES',
            '064': 'IMUES',
            '067': 'IPIALES',
            '073': 'LA CRUZ',
            '076': 'LA FLORIDA',
            '077': 'LA LLANADA',
            '078': 'LA TOLA',
            '079': 'LA UNION',
            '080': 'LEIVA',
            '082': 'LINARES',
            '085': 'LOS ANDES (SOTOMAYOR)',
            '088': 'MAGUI (PAYAN)',
            '091': 'MALLAMA (PIEDRANCHA)',
            '094': 'MOSQUERA',
            '095': 'OLAYA HERRERA',
            '096': 'NARI/O',
            '097': 'OSPINA',
            '098': 'POLICARPA',
            '100': 'POTOSI',
            '101': 'PROVIDENCIA',
            '103': 'PUERRES',
            '106': 'PUPIALES',
            '109': 'RICAURTE',
            '112': 'ROBERTO PAYAN (SAN JOSE)',
            '115': 'SAMANIEGO',
            '118': 'SANDONA',
            '120': 'SAN BERNARDO',
            '121': 'SAN LORENZO',
            '123': 'SAN PEDRO DE CARTAGO',
            '124': 'SAN PABLO',
            '125': 'SANTA BARBARA (ISCUANDE)',
            '127': 'SANTACRUZ (GUACHAVES)',
            '130': 'SAPUYES',
            '133': 'TAMINANGO',
            '136': 'TANGUA',
            '139': 'TUMACO',
            '142': 'TUQUERRES',
            '145': 'YACUANQUER',
        },
    },
    "24": {
        'name': 'RISARALDA',
        'municipality': {
            '001': 'PEREIRA',
            '008': 'APIA',
            '013': 'BALBOA',
            '021': 'BELEN DE UMBRIA',
            '025': 'DOSQUEBRADAS',
            '029': 'GUATICA',
            '038': 'LA CELIA',
            '046': 'LA VIRGINIA',
            '054': 'MARSELLA',
            '062': 'MISTRATO',
            '070': 'PUEBLO RICO',
            '078': 'QUINCHIA',
            '086': 'SANTA ROSA DE CABAL',
            '094': 'SANTUARIO',
        },
    },
    "25": {
        'name': 'NORTE DE SANTANDER',
        'municipality': {
            '001': 'CUCUTA',
            '004': 'ABREGO',
            '007': 'ARBOLEDAS',
            '010': 'BOCHALEMA',
            '013': 'BUCARASICA',
            '016': 'CACOTA',
            '019': 'CACHIRA',
            '022': 'CONVENCION',
            '025': 'CUCUTILLA',
            '028': 'CHINACOTA',
            '031': 'CHITAGA',
            '034': 'DURANIA',
            '036': 'EL TARRA',
            '037': 'EL CARMEN',
            '038': 'EL ZULIA',
            '040': 'GRAMALOTE',
            '043': 'HACARI',
            '046': 'HERRAN',
            '049': 'LABATECA',
            '051': 'LA ESPERANZA',
            '052': 'LA PLAYA',
            '054': 'LOS PATIOS',
            '055': 'LOURDES',
            '058': 'MUTISCUA',
            '061': 'OCA/A',
            '064': 'PAMPLONA',
            '067': 'PAMPLONITA',
            '069': 'PUERTO SANTANDER',
            '070': 'RAGONVALIA',
            '073': 'SALAZAR',
            '076': 'SAN CALIXTO',
            '079': 'SAN CAYETANO',
            '082': 'SANTIAGO',
            '085': 'SARDINATA',
            '088': 'SILOS',
            '091': 'TEORAMA',
            '093': 'TIBU',
            '094': 'TOLEDO',
            '097': 'VILLA CARO',
            '100': 'VILLA DEL ROSARIO',
        },
    },
    "26": {
        'name': 'QUINDIO',
        'municipality': {
            '001': 'ARMENIA',
            '005': 'BUENAVISTA',
            '010': 'CALARCA',
            '020': 'CIRCASIA',
            '025': 'CORDOBA',
            '030': 'FILANDIA',
            '040': 'GENOVA',
            '050': 'LA TEBAIDA',
            '060': 'MONTENEGRO',
            '070': 'PIJAO',
            '080': 'QUIMBAYA',
            '090': 'SALENTO',
        },
    },
    "27": {
        'name': 'SANTANDER',
        'municipality': {
            '001': 'BUCARAMANGA',
            '004': 'AGUADA',
            '007': 'ALBANIA',
            '010': 'ARATOCA',
            '013': 'BARBOSA',
            '016': 'BARICHARA',
            '019': 'BARRANCABERMEJA',
            '022': 'BETULIA',
            '025': 'BOLIVAR',
            '028': 'CABRERA',
            '031': 'CALIFORNIA',
            '034': 'CAPITANEJO',
            '037': 'CARCASI',
            '040': 'CEPITA',
            '043': 'CERRITO',
            '045': 'CIMITARRA',
            '046': 'CONCEPCION',
            '049': 'CONFINES',
            '052': 'CONTRATACION',
            '055': 'COROMORO',
            '058': 'CURITI',
            '061': 'CHARALA',
            '064': 'CHARTA',
            '067': 'CHIMA',
            '070': 'CHIPATA',
            '071': 'EL CARMEN',
            '073': 'EL GUACAMAYO',
            '074': 'EL PLAYON',
            '075': 'EL PE/ON',
            '076': 'ENCINO',
            '079': 'ENCISO',
            '080': 'FLORIAN',
            '082': 'FLORIDABLANCA',
            '085': 'GALAN',
            '088': 'GAMBITA',
            '091': 'GIRON',
            '094': 'GUACA',
            '097': 'GUADALUPE',
            '100': 'GUAPOTA',
            '103': 'GUAVATA',
            '106': 'GUEPSA',
            '109': 'HATO',
            '112': 'JESUS MARIA',
            '115': 'JORDAN',
            '118': 'LA PAZ',
            '119': 'LA BELLEZA',
            '120': 'LANDAZURI',
            '121': 'LEBRIJA',
            '124': 'LOS SANTOS',
            '127': 'MACARAVITA',
            '130': 'MALAGA',
            '133': 'MATANZA',
            '136': 'MOGOTES',
            '139': 'MOLAGAVITA',
            '142': 'OCAMONTE',
            '145': 'OIBA',
            '148': 'ONZAGA',
            '151': 'PALMAR',
            '154': 'PALMAS DEL SOCORRO',
            '157': 'PARAMO',
            '160': 'PIEDECUESTA',
            '163': 'PINCHOTE',
            '166': 'PUENTE NACIONAL',
            '167': 'PUERTO PARRA',
            '169': 'PUERTO WILCHES',
            '172': 'RIONEGRO',
            '174': 'SABANA DE TORRES',
            '175': 'SAN ANDRES',
            '178': 'SAN BENITO',
            '181': 'SAN GIL',
            '184': 'SAN JOAQUIN',
            '187': 'SAN JOSE DE MIRANDA',
            '190': 'SAN MIGUEL',
            '193': 'SAN VICENTE DE CHUCURI',
            '194': 'SANTA HELENA DEL OPON',
            '195': 'SANTA BARBARA',
            '196': 'SIMACOTA',
            '199': 'SOCORRO',
            '202': 'SUAITA',
            '205': 'SUCRE',
            '208': 'SURATA',
            '211': 'TONA',
            '217': 'VALLE DE SAN JOSE',
            '219': 'VETAS',
            '220': 'VELEZ',
            '221': 'VILLANUEVA',
            '223': 'ZAPATOCA',
        },
    },
    "28": {
        'name': 'SUCRE',
        'municipality': {
            '001':'SINCELEJO',
            '010':'BUENAVISTA',
            '020':'CAIMITO',
            '030':'COLOSO (RICAURTE)',
            '040':'COROZAL',
            '041':'COVE/AS',
            '042':'EL ROBLE',
            '045':'CHALAN',
            '048':'GALERAS (NUEVA GRANADA)',
            '049':'GUARANDA',
            '050':'LA UNION',
            '055':'LOS PALMITOS',
            '060':'MAJAGUAL',
            '080':'MORROA',
            '100':'OVEJAS',
            '120':'PALMITO',
            '160':'SAMPUES',
            '180':'SAN BENITO ABAD',
            '190':'SAN JUAN DE BETULIA (BETULIA)',
            '200':'SAN MARCOS',
            '220':'SAN ONOFRE',
            '240':'SAN PEDRO',
            '260':'SINCE',
            '280':'SUCRE',
            '300':'TOLU',
            '320':'TOLUVIEJO',
        },
    },
    "29": {
        'name': 'TOLIMA',
        'municipality': {
            '001':'IBAGUE',
            '004':'ALPUJARRA',
            '007':'ALVARADO',
            '010':'AMBALEMA',
            '013':'ANZOATEGUI',
            '016':'ARMERO (GUAYABAL)',
            '019':'ATACO',
            '022':'CAJAMARCA',
            '025':'CARMEN DE APICALA',
            '028':'CASABIANCA',
            '031':'COELLO',
            '034':'COYAIMA',
            '037':'CUNDAY',
            '040':'CHAPARRAL',
            '043':'DOLORES',
            '046':'ESPINAL',
            '049':'FALAN',
            '052':'FLANDES',
            '055':'FRESNO',
            '058':'GUAMO',
            '061':'HERVEO',
            '064':'HONDA',
            '067':'ICONONZO',
            '070':'LERIDA',
            '073':'LIBANO',
            '076':'MARIQUITA',
            '079':'MELGAR',
            '080':'MURILLO',
            '082':'NATAGAIMA',
            '085':'ORTEGA',
            '087':'PALOCABILDO',
            '088':'PIEDRAS',
            '089':'PLANADAS',
            '091':'PRADO',
            '094':'PURIFICACION',
            '097':'RIOBLANCO',
            '100':'RONCESVALLES',
            '103':'ROVIRA',
            '105':'SALDA/A',
            '106':'SAN ANTONIO',
            '109':'SAN LUIS',
            '112':'SANTA ISABEL',
            '115':'SUAREZ',
            '118':'VALLE DE SAN JUAN',
            '121':'VENADILLO',
            '124':'VILLAHERMOSA',
            '127':'VILLARRICA',
        },
    },
    "31": {
        'name': 'VALLE',
        'municipality': {
            '001':'CALI',
            '004':'ALCALA',
            '007':'ANDALUCIA',
            '010':'ANSERMANUEVO',
            '013':'ARGELIA',
            '016':'BOLIVAR',
            '019':'BUENAVENTURA',
            '022':'BUGA',
            '025':'BUGALAGRANDE',
            '028':'CAICEDONIA',
            '031':'CANDELARIA',
            '034':'CARTAGO',
            '037':'DAGUA',
            '040':'CALIMA (DARIEN)',
            '043':'EL AGUILA',
            '046':'EL CAIRO',
            '049':'EL CERRITO',
            '052':'EL DOVIO',
            '055':'FLORIDA',
            '058':'GINEBRA',
            '061':'GUACARI',
            '064':'JAmunicipalityDI',
            '067':'LA CUMBRE',
            '070':'LA UNION',
            '073':'LA VICTORIA',
            '076':'OBANDO',
            '079':'PALMIRA',
            '082':'PRADERA',
            '085':'RESTREPO',
            '088':'RIOFRIO',
            '091':'ROLDANILLO',
            '094':'SAN PEDRO',
            '097':'SEVILLA',
            '100':'TORO',
            '103':'TRUJILLO',
            '106':'TULUA',
            '109':'ULLOA',
            '112':'VERSALLES',
            '115':'VIJES',
            '118':'YOTOCO',
            '121':'YUMBO',
            '124':'ZARZAL',
        },
    },
    "40": {
        'name': 'ARAUCA',
        'municipality': {
            '001':'ARAUCA',
            '005':'TAME',
            '010':'ARAUQUITA',
            '015':'CRAVO NORTE',
            '017':'FORTUL',
            '020':'PUERTO RONDON',
            '025':'SARAVENA',
        },
    },
    "44": {
        'name': 'CAQUETA',
        'municipality': {
            '001':'FLORENCIA',
            '002':'ALBANIA',
            '003':'CARTAGENA DEL CHAIRA',
            '004':'BELEN DE LOS ANDAQUIES',
            '005':'EL DONCELLO',
            '006':'EL PAUJIL',
            '007':'LA MONTA/ITA',
            '009':'PUERTO RICO',
            '010':'SAN VICENTE DEL CAGUAN',
            '012':'CURILLO',
            '016':'MILAN',
            '017':'MORELIA',
            '020':'SAN JOSE DEL FRAGUA',
            '022':'SOLANO',
            '024':'SOLITA',
            '040':'VALPARAISO',
        },
    },
    "46": {
        'name': 'CASANARE',
        'municipality': {
            '001':'YOPAL',
            '040':'AGUAZUL',
            '120':'CHAMEZA',
            '320':'HATO COROZAL',
            '480':'LA SALINA',
            '520':'MANI',
            '540':'MONTERREY',
            '560':'NUNCHIA',
            '640':'OROCUE',
            '680':'PAZ DE ARIPORO (MORENO)',
            '700':'PORE',
            '760':'RECETOR',
            '800':'SABANALARGA',
            '815':'SACAMA',
            '830':'SAN LUIS DE PALENQUE',
            '840':'TAMARA',
            '850':'TAURAMENA',
            '865':'TRINIDAD',
            '880':'VILLANUEVA',
        },
    },
    "48": {
        'name': 'LA GUAJIRA',
        'municipality': {
            '001':'RIOHACHA',
            '002':'ALBANIA',
            '004':'BARRANCAS',
            '005':'DIBULLA',
            '006':'EL MOLINO',
            '007':'FONSECA',
            '008':'DISTRACCION',
            '009':'HATONUEVO',
            '010':'MAICAO',
            '011':'MANAURE',
            '012':'LA JAGUA DEL PILAR',
            '013':'SAN JUAN DEL CESAR',
            '016':'URIBIA',
            '018':'URUMITA',
            '020':'VILLANUEVA',
        },
    },
    "50": {
        'name': 'GUAINIA',
        'municipality': {
            '001':'INIRIDA',
            '050':'MAPIRIPANA',
            '070':'BARRANCO MINAS',
            '073':'CACAHUAL',
            '078':'LA GUADALUPE',
            '083':'MORICHAL (MORICHAL NUEVO)',
            '087':'PANA PANA (CAMPO ALEGRE)',
            '090':'PUERTO COLOMBIA',
            '092':'SAN FELIPE',
        },
    },
    "52": {
        'name': 'META',
        'municipality': {
            '001':'VILLAVICENCIO',
            '005':'ACACIAS',
            '006':'BARRANCA DE UPIA',
            '008':'CABUYARO',
            '010':'CASTILLA LA NUEVA',
            '015':'CUBARRAL',
            '020':'CUMARAL',
            '025':'EL CALVARIO',
            '027':'EL CASTILLO',
            '028':'EL DORADO',
            '030':'FUENTE DE ORO',
            '035':'GRANADA',
            '040':'GUAMAL',
            '041':'LA MACARENA',
            '042':'LEJANIAS',
            '043':'PUERTO GAITAN',
            '044':'MESETAS',
            '045':'PUERTO LOPEZ',
            '046':'MAPIRIPAN',
            '047':'PUERTO CONCORDIA',
            '048':'PUERTO LLERAS',
            '049':'PUERTO RICO',
            '050':'RESTREPO',
            '055':'SAN CARLOS DE GUAROA',
            '058':'SAN JUAN DE ARAMA',
            '059':'SAN JUANITO',
            '060':'SAN MARTIN DE LOS LLANOS',
            '074':'URIBE',
            '080':'VISTA HERMOSA',
        },
    },
    "54": {
        'name': 'GUAVIARE',
        'municipality': {
            '001':'SAN JOSE DEL GUAVIARE',
            '003':'CALAMAR',
            '007':'EL RETORNO',
            '012':'MIRAFLORES',
        },
    },
    "56": {
        'name': 'SAN ANDRES',
        'municipality': {
            '001':'SAN ANDRES',
            '004':'PROVIDENCIA',
        },
    },
    "60": {
        'name': 'AMAZONAS',
        'municipality': {
            '001':'LETICIA',
            '007':'PUERTO NARI/O',
            '010':'EL ENCANTO',
            '013':'LA CHORRERA',
            '016':'LA PEDRERA',
            '017':'LA VICTORIA',
            '019':'MIRITI PARANA',
            '021':'PUERTO SANTANDER',
            '022':'TARAPACA',
            '030':'PUERTO ALEGRIA',
            '040':'PUERTO ARICA',
        },
    },
    "64": {
        'name': 'PUTUMAYO',
        'municipality': {
            '001':'MOCOA',
            '002':'PUERTO ASIS',
            '004':'PUERTO LEGUIZAMO',
            '007':'COLON',
            '013':'SAN FRANCISCO',
            '016':'SANTIAGO',
            '018':'SAN MIGUEL (LA DORADA)',
            '019':'SIBUNDOY',
            '023':'ORITO',
            '025':'PUERTO GUZMAN',
            '026':'PUERTO CAICEDO',
            '028':'VALLE DEL GUAMUEZ (LA HORMIGA)',
            '030':'VILLAGARZON',
        },
    },
    "68": {
        'name': 'VAUPES',
        'municipality': {
            '001':'MITU',
            '004':'CARURU',
            '010':'MORICHAL (PAPUNAGUA)',
            '013':'BUENOS AIRES (PACOA)',
            '017':'TARAIRA',
            '022':'YAVARATE',
        },
    },
    "72": {
        'name': 'VICHADA',
        'municipality': {
            '001':'PUERTO CARRE/O',
            '002':'SANTA ROSALIA',
            '006':'CUMARIBO',
            '008':'LA PRIMAVERA',
        },
    },
    "88": {
        'name': 'CONSULADOS',
        'municipality': {
            '120':'ALEMANIA',
            '140':'PAISES BAJ‐ANTILLAS HOLANDESAS',
            '155':'ARGENTINA',
            '160':'PAISES BAJOS ‐ ARUBA',
            '165':'AUSTRALIA',
            '170':'AUSTRIA',
            '185':'BARBADOS',
            '190':'BELGICA',
            '195':'BELICE',
            '215':'BOLIVIA',
            '220':'BRASIL',
            '250':'CANADA',
            '275':'COREA DEL SUR',
            '285':'COSTA RICA',
            '290':'CUBA',
            '300':'CHECOSLOVAQUIA',
            '305':'CHILE',
            '315':'CHINA REPUBLICA POPULAR',
            '320':'CHIPRE',
            '325':'DINAMARCA',
            '330':'ECUADOR',
            '335':'EGIPTO',
            '340':'EL SALVADOR',
            '355':'ESPA/A',
            '360':'ESTADOS UNIDOS',
            '370':'FILIPINAS',
            '375':'FINLANDIA',
            '380':'FRANCIA',
            '405':'GRECIA',
            '410':'GUATEMALA',
            '425':'GUYANA',
            '430':'HAITI',
            '435':'HOLANDA',
            '440':'HONDURAS',
            '450':'HUNGRIA REPUBLICA POPULAR',
            '455':'INDIA',
            '460':'INDONESIA',
            '465':'INGLATERRA',
            '475':'IRAN',
            '480':'IRLANDA',
            '490':'ISRAEL',
            '495':'ITALIA',
            '500':'JAMAICA',
            '505':'JAPON',
            '515':'KENIA',
            '535':'LIBANO',
            '560':'MALASIA',
            '580':'MARRUECOS',
            '590':'MEXICO',
            '620':'NICARAGUA',
            '635':'NORUEGA',
            '655':'PANAMA',
            '665':'PARAGUAY',
            '670':'PERU',
            '675':'POLONIA',
            '680':'PORTUGAL',
            '683':'PUERTO RICO',
            '685':'REPUBLICA DOMINICANA',
            '695':'RUMANIA REPUBLICA SOCIAL',
            '700':'RUSIA',
            '745':'SUDAFRICA',
            '755':'SUECIA',
            '760':'SUIZA',
            '770':'TURQUIA',
            '785':'TRINIDAD Y TOBAGO',
            '805':'URUGUAY',
            '815':'VENEZUELA',
        },
    },
}

def search_site(departament_id, municipality_id):
    # get departament with the id
    departament = sites[departament_id]
    # get the name of the departament
    departament_name = departament['name']
    # get the municipalities of the departament
    municipalities = departament['municipality']
    # get the municipality name with the id
    municipality_name = municipalities[municipality_id]
    # setting the response in a dict
    response = {
        'departament' : departament_name,
        'municipality' : municipality_name
    }
    return response # return the response